### ISSUE TITLE
Issue in Firefox

### ISSUE THREAD

**Issue by ddulic** [bartholomej/material-scrolltop#1]
Hello, kinda a newbie here. Loved your script and edited it to work with my website but it seems to not be working in Firefox and I cannot figure out why :/ It works edited offline on your demo, but once I upload it to my website it gets broken in FireFox. Here is the website in question: http://dulic.me/about
Would love it if you could help me out. Thanks.

**Comment by bartholomej** [comment]
Hi Damir, I've tried your implementation and you're right.
Now **should be fixed** ;) Please, update plugin `bower update` (or manually [v0.6.4](https://github.com/bartholomej/material-scrolltop/releases/tag/v0.6.4))
Let me know how does it work. Thx ;)

**Comment by ddulic** [comment]
Its fixed now. Thank you for the fast response and fix ^^
