### ISSUE TITLE
Consider tweaking your build process

### ISSUE THREAD

**Issue by paxperscientiam** [bartholomej/material-scrolltop#12]
Problem:
node-sass does not like the following:
1. importing css
2. importing file with explicit extension.
3. gets confused when there are files with same basename, but extensions css, and scss.

If you save material-scrolltop.css to, say, dist/, then this issue would be resolved.

**Comment by bartholomej** [comment]
@paxperscientiam Hi Chris, thank you for your contribution.
Here is the sneak peek of new version. Build process was radically updated and source code was rewritten into TypeScript.  
_Don't worry, build is still with jQuery_ :)
https://github.com/bartholomej/material-scrolltop/tree/tooling-tsc

Feel free to share your feedback.
