### ISSUE TITLE
Move to npm for yarn support

### ISSUE THREAD

**Issue by favna** [bartholomej/material-scrolltop#4]
Bower is on its way out in web development in favor of yarn which works with the npm registry. As yarn [currently does not support bower](https://bower.io/blog/2016/using-bower-with-yarn/) it would be great if this package could be made available on to npm registry.

[Also see this pull request on the yarn repo](https://github.com/yarnpkg/yarn/pull/1441)

[And this blog article on moving from bower to yarn](https://bower.io/blog/2017/how-to-migrate-away-from-bower/)

**Comment by bartholomej** [comment]
@Favna You're absolutely right! Thanks for your contribution here.

Now you can install it from npm registry as well. Try it and let me know ;)
```yarn material-scrolltop```
or
```npm install material-scrolltop --save```

**Comment by favna** [comment]
works A-ok! 

```sh
$ yarn add material-scrolltop
yarn add v1.3.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > material-scrolltop@1.0.0" has unmet peer dependency "jquery@>=1.7".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ material-scrolltop@1.0.0
Done in 2.17s.
```

Ignore the unmet peer dependency, that's because I tried in a completely otherwise empty folder.
